package com.example.ui.util

import com.example.data.model.AppLanguage

object Localization {
    fun tr(key: String, language: AppLanguage): String {
        val map = when (language) {
            AppLanguage.HINDI -> hindiMap
            AppLanguage.SPANISH -> spanishMap
            AppLanguage.FRENCH -> frenchMap
            AppLanguage.GERMAN -> germanMap
            AppLanguage.ARABIC -> arabicMap
            AppLanguage.BENGALI -> bengaliMap
            AppLanguage.MARATHI -> marathiMap
            AppLanguage.TELUGU -> teluguMap
            AppLanguage.TAMIL -> tamilMap
            AppLanguage.GUJARATI -> gujaratiMap
            AppLanguage.KANNADA -> kannadaMap
            AppLanguage.PUNJABI -> punjabiMap
            AppLanguage.MALAYALAM -> malayalamMap
            AppLanguage.ODIA -> odiaMap
            AppLanguage.URDU -> urduMap
            AppLanguage.BHOJPURI -> bhojpuriMap
            AppLanguage.PORTUGUESE -> portugueseMap
            AppLanguage.RUSSIAN -> russianMap
            AppLanguage.CHINESE -> chineseMap
            AppLanguage.JAPANESE -> japaneseMap
            AppLanguage.ENGLISH -> englishMap
        }
        return map[key] ?: englishMap[key] ?: key
    }

    val englishMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Manage • Build • Succeed",
        "dashboard" to "Dashboard",
        "projects" to "Projects",
        "attendance" to "Attendance",
        "tasks" to "Tasks",
        "materials" to "Materials",
        "expenses" to "Expenses",
        "staff" to "Staff",
        "reports" to "Reports",
        "profile" to "Profile",
        "settings" to "Settings",
        "more" to "More",
        "ai_chat" to "AI Assistant",
        "ai_fill" to "AI Auto-Fill",
        "ask_ai" to "Ask SITE MAN AI",
        "today_attendance" to "Today's Attendance",
        "ongoing_projects" to "Ongoing Projects",
        "pending_tasks" to "Pending Tasks",
        "low_stock" to "Low Stock Alert",
        "project_health" to "Project Health",
        "quick_actions" to "Quick Actions",
        "ai_insights" to "AI Insights & Alerts",
        "weather_safety" to "Site Weather & Safety",
        "scan_bill" to "Scan Bill / OCR",
        "check_in" to "Check In",
        "check_out" to "Check Out",
        "create_project" to "New Project",
        "add_project" to "Add Project",
        "create_task" to "New Task",
        "add_task" to "Add Task",
        "add_expense" to "Add Expense",
        "add_material" to "Add Material",
        "add_staff" to "Add Staff",
        "generate_report" to "Generate Report",
        "voice_speak" to "Voice Dictate",
        "role" to "Role",
        "language" to "Language",
        "budget" to "Budget",
        "spent" to "Spent",
        "progress" to "Progress",
        "search" to "Search...",
        "filter" to "Filter",
        "all" to "All",
        "active" to "Active",
        "planning" to "Planning",
        "completed" to "Completed",
        "on_hold" to "On Hold",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "status" to "Status",
        "priority" to "Priority",
        "present" to "Present",
        "absent" to "Absent",
        "half_day" to "Half Day",
        "on_leave" to "On Leave",
        "overtime" to "Overtime",
        "late" to "Late",
        "camera_scan" to "Camera Scan",
        "ai_thinking" to "SITE MAN AI is thinking...",
        "ai_speaking" to "AI is speaking...",
        "auto_speak" to "Auto-Speak Answers",
        "speak_again" to "Speak Aloud",
        "stop_speaking" to "Stop Audio",
        "clear_history" to "Clear History",
        "voice_input" to "Tap to Speak in any Language",
        "quick_questions_title" to "Instant AI Questions",
        "dark_mode" to "Dark Mode",
        "ai_suggestions" to "AI Real-Time Suggestions",
        "voice_recognition" to "Voice Recognition",
        "reset_data" to "Reset Demo Data",
        "logout" to "Logout"
    )

    private val hindiMap = mapOf(
        "app_title" to "साइट मैन",
        "tagline" to "प्रबंधन • निर्माण • सफलता",
        "dashboard" to "डैशबोर्ड",
        "projects" to "प्रोजेक्ट्स",
        "attendance" to "हाजिरी (अटेंडेंस)",
        "tasks" to "कार्य (टास्क)",
        "materials" to "सामग्री (मटेरियल)",
        "expenses" to "खर्चे (एक्सपेंस)",
        "staff" to "कर्मचारी (स्टाफ)",
        "reports" to "रिपोर्ट्स",
        "profile" to "प्रोफाइल",
        "settings" to "सेटिंग्स",
        "more" to "अधिक",
        "ai_chat" to "एआई सहायक",
        "ai_fill" to "एआई ऑटो-फिल",
        "ask_ai" to "साइट मैन एआई से पूछें",
        "today_attendance" to "आज की हाजिरी",
        "ongoing_projects" to "चल रहे प्रोजेक्ट्स",
        "pending_tasks" to "बकाया कार्य",
        "low_stock" to "कम स्टॉक चेतावनी",
        "project_health" to "प्रोजेक्ट स्थिति व स्वास्थ्य",
        "quick_actions" to "त्वरित कार्य",
        "ai_insights" to "एआई सुझाव व अलर्ट",
        "weather_safety" to "साइट मौसम व सुरक्षा",
        "scan_bill" to "बिल स्कैन करें",
        "check_in" to "चेक इन करें",
        "check_out" to "चेक आउट करें",
        "create_project" to "नया प्रोजेक्ट",
        "add_project" to "प्रोजेक्ट जोड़ें",
        "create_task" to "नया टास्क",
        "add_task" to "टास्क जोड़ें",
        "add_expense" to "खर्चा दर्ज करें",
        "add_material" to "सामग्री जोड़ें",
        "add_staff" to "स्टाफ जोड़ें",
        "generate_report" to "रिपोर्ट तैयार करें",
        "voice_speak" to "बोलकर दर्ज करें",
        "role" to "भूमिका",
        "language" to "भाषा",
        "budget" to "बजट",
        "spent" to "खर्च हुआ",
        "progress" to "प्रगति",
        "search" to "खोजें...",
        "filter" to "फ़िल्टर",
        "all" to "सभी",
        "active" to "सक्रिय",
        "planning" to "योजना",
        "completed" to "पूर्ण",
        "on_hold" to "रुका हुआ",
        "save" to "सहेजें",
        "cancel" to "रद्द करें",
        "delete" to "हटाएं",
        "edit" to "संपादित करें",
        "status" to "स्थिति",
        "priority" to "प्राथमिकता",
        "present" to "उपस्थित",
        "absent" to "अनुपस्थित",
        "half_day" to "आधा दिन",
        "on_leave" to "छुट्टी",
        "overtime" to "ओवरटाइम",
        "late" to "देर से",
        "camera_scan" to "कैमरा स्कैन",
        "ai_thinking" to "साइट मैन एआई सोच रहा है...",
        "ai_speaking" to "एआई बोल रहा है...",
        "auto_speak" to "उत्तर स्वतः बोलें",
        "speak_again" to "आवाज़ में सुनें",
        "stop_speaking" to "आवाज़ रोकें",
        "clear_history" to "इतिहास साफ़ करें",
        "voice_input" to "किसी भी भाषा में बोलें",
        "quick_questions_title" to "त्वरित एआई प्रश्न",
        "dark_mode" to "डार्क मोड",
        "ai_suggestions" to "एआई त्वरित सुझाव",
        "voice_recognition" to "वॉयस पहचान",
        "reset_data" to "डेमो डेटा रीसेट करें",
        "logout" to "लॉगआउट"
    )

    private val spanishMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Gestionar • Construir • Triunfar",
        "dashboard" to "Panel",
        "projects" to "Proyectos",
        "attendance" to "Asistencia",
        "tasks" to "Tareas",
        "materials" to "Materiales",
        "expenses" to "Gastos",
        "staff" to "Personal",
        "reports" to "Informes",
        "profile" to "Perfil",
        "settings" to "Ajustes",
        "more" to "Más",
        "ai_chat" to "Asistente IA",
        "ai_fill" to "Autollenado IA",
        "ask_ai" to "Preguntar a SITE MAN IA",
        "today_attendance" to "Asistencia de Hoy",
        "ongoing_projects" to "Proyectos en Curso",
        "pending_tasks" to "Tareas Pendientes",
        "low_stock" to "Alerta de Stock Bajo",
        "project_health" to "Salud del Proyecto",
        "quick_actions" to "Acciones Rápidas",
        "ai_insights" to "Recomendaciones IA",
        "weather_safety" to "Clima y Seguridad",
        "scan_bill" to "Escanear Factura",
        "check_in" to "Registrar Entrada",
        "check_out" to "Registrar Salida",
        "create_project" to "Nuevo Proyecto",
        "add_project" to "Añadir Proyecto",
        "create_task" to "Nueva Tarea",
        "add_task" to "Añadir Tarea",
        "add_expense" to "Registrar Gasto",
        "add_material" to "Añadir Material",
        "add_staff" to "Añadir Personal",
        "generate_report" to "Generar Informe",
        "voice_speak" to "Dictado por Voz",
        "role" to "Rol",
        "language" to "Idioma",
        "budget" to "Presupuesto",
        "spent" to "Gastado",
        "progress" to "Progreso",
        "search" to "Buscar...",
        "filter" to "Filtrar",
        "all" to "Todos",
        "active" to "Activo",
        "planning" to "Planificación",
        "completed" to "Completado",
        "on_hold" to "En Pausa",
        "save" to "Guardar",
        "cancel" to "Cancelar",
        "delete" to "Eliminar",
        "edit" to "Editar",
        "status" to "Estado",
        "priority" to "Prioridad",
        "present" to "Presente",
        "absent" to "Ausente",
        "half_day" to "Medio Día",
        "on_leave" to "De Permiso",
        "overtime" to "Horas Extras",
        "late" to "Tarde",
        "camera_scan" to "Escanear con Cámara",
        "ai_thinking" to "La IA está pensando...",
        "ai_speaking" to "La IA está hablando...",
        "auto_speak" to "Voz Automática",
        "speak_again" to "Escuchar",
        "stop_speaking" to "Detener Audio",
        "clear_history" to "Borrar Historial",
        "voice_input" to "Hable en cualquier idioma",
        "quick_questions_title" to "Preguntas Rápidas IA",
        "dark_mode" to "Modo Oscuro",
        "ai_suggestions" to "Sugerencias IA",
        "voice_recognition" to "Reconocimiento de Voz",
        "reset_data" to "Restablecer Datos",
        "logout" to "Cerrar Sesión"
    )

    private val frenchMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Gérer • Construire • Réussir",
        "dashboard" to "Tableau de bord",
        "projects" to "Projets",
        "attendance" to "Présence",
        "tasks" to "Tâches",
        "materials" to "Matériaux",
        "expenses" to "Dépenses",
        "staff" to "Personnel",
        "reports" to "Rapports",
        "profile" to "Profil",
        "settings" to "Paramètres",
        "more" to "Plus",
        "ai_chat" to "Assistant IA",
        "ai_fill" to "Remplissage IA",
        "ask_ai" to "Demander à l'IA",
        "today_attendance" to "Présence du jour",
        "ongoing_projects" to "Projets en cours",
        "pending_tasks" to "Tâches en attente",
        "low_stock" to "Stock faible",
        "project_health" to "Santé du chantier",
        "quick_actions" to "Actions rapides",
        "ai_insights" to "Analyses IA",
        "weather_safety" to "Météo et Sécurité",
        "scan_bill" to "Scanner Facture",
        "check_in" to "Pointer Arrivée",
        "check_out" to "Pointer Départ",
        "create_project" to "Nouveau Projet",
        "add_project" to "Ajouter Projet",
        "create_task" to "Nouvelle Tâche",
        "add_task" to "Ajouter Tâche",
        "add_expense" to "Ajouter Dépense",
        "add_material" to "Ajouter Matériau",
        "add_staff" to "Ajouter Personnel",
        "generate_report" to "Générer Rapport",
        "voice_speak" to "Dictée Vocale",
        "role" to "Rôle",
        "language" to "Langue",
        "budget" to "Budget",
        "spent" to "Dépensé",
        "progress" to "Progression",
        "search" to "Rechercher...",
        "filter" to "Filtrer",
        "all" to "Tous",
        "active" to "Actif",
        "planning" to "Planification",
        "completed" to "Terminé",
        "on_hold" to "En Pause",
        "save" to "Enregistrer",
        "cancel" to "Annuler",
        "delete" to "Supprimer",
        "edit" to "Modifier",
        "status" to "Statut",
        "priority" to "Priorité",
        "present" to "Présent",
        "absent" to "Absent",
        "half_day" to "Demi-journée",
        "on_leave" to "En congé",
        "overtime" to "Heures sup.",
        "late" to "En retard",
        "camera_scan" to "Scanner avec Caméra",
        "ai_thinking" to "L'IA réfléchit...",
        "ai_speaking" to "L'IA parle...",
        "auto_speak" to "Lecture Vocale Auto",
        "speak_again" to "Écouter",
        "stop_speaking" to "Arrêter Audio",
        "clear_history" to "Effacer l'historique",
        "voice_input" to "Parlez dans n'importe quelle langue",
        "quick_questions_title" to "Questions Rapides IA",
        "dark_mode" to "Mode Sombre",
        "ai_suggestions" to "Suggestions IA",
        "voice_recognition" to "Reconnaissance Vocale",
        "reset_data" to "Réinitialiser",
        "logout" to "Déconnexion"
    )

    private val germanMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Verwalten • Bauen • Gelingen",
        "dashboard" to "Dashboard",
        "projects" to "Projekte",
        "attendance" to "Anwesenheit",
        "tasks" to "Aufgaben",
        "materials" to "Baustoffe",
        "expenses" to "Ausgaben",
        "staff" to "Personal",
        "reports" to "Berichte",
        "profile" to "Profil",
        "settings" to "Einstellungen",
        "more" to "Mehr",
        "ai_chat" to "KI-Assistent",
        "ai_fill" to "KI-Autoausfüllen",
        "ask_ai" to "SITE MAN KI fragen",
        "today_attendance" to "Heutige Anwesenheit",
        "ongoing_projects" to "Laufende Projekte",
        "pending_tasks" to "Offene Aufgaben",
        "low_stock" to "Niedriger Bestand",
        "project_health" to "Projektstatus",
        "quick_actions" to "Schnellaktionen",
        "ai_insights" to "KI-Empfehlungen",
        "weather_safety" to "Wetter & Sicherheit",
        "scan_bill" to "Rechnung scannen",
        "check_in" to "Einchecken",
        "check_out" to "Auschecken",
        "create_project" to "Neues Projekt",
        "add_project" to "Projekt hinzufügen",
        "create_task" to "Neue Aufgabe",
        "add_task" to "Aufgabe hinzufügen",
        "add_expense" to "Ausgabe erfassen",
        "add_material" to "Material erfassen",
        "add_staff" to "Mitarbeiter hinzufügen",
        "generate_report" to "Bericht erstellen",
        "voice_speak" to "Spracheingabe",
        "role" to "Rolle",
        "language" to "Sprache",
        "budget" to "Budget",
        "spent" to "Ausgegeben",
        "progress" to "Fortschritt",
        "search" to "Suchen...",
        "filter" to "Filtern",
        "all" to "Alle",
        "active" to "Aktiv",
        "planning" to "Planung",
        "completed" to "Abgeschlossen",
        "on_hold" to "Pausiert",
        "save" to "Speichern",
        "cancel" to "Abbrechen",
        "delete" to "Löschen",
        "edit" to "Bearbeiten",
        "status" to "Status",
        "priority" to "Priorität",
        "present" to "Anwesend",
        "absent" to "Abwesend",
        "half_day" to "Halber Tag",
        "on_leave" to "Urlaub",
        "overtime" to "Überstunden",
        "late" to "Verspätet",
        "camera_scan" to "Kamera-Scan",
        "ai_thinking" to "KI verarbeitet...",
        "ai_speaking" to "KI spricht...",
        "auto_speak" to "Automatisch vorlesen",
        "speak_again" to "Vorlesen",
        "stop_speaking" to "Audio stoppen",
        "clear_history" to "Verlauf löschen",
        "voice_input" to "In beliebiger Sprache sprechen",
        "quick_questions_title" to "Sofortige KI-Fragen",
        "dark_mode" to "Dunkelmodus",
        "ai_suggestions" to "KI-Vorschläge",
        "voice_recognition" to "Spracherkennung",
        "reset_data" to "Daten zurücksetzen",
        "logout" to "Abmelden"
    )

    private val arabicMap = mapOf(
        "app_title" to "سايت مان",
        "tagline" to "إدارة • بناء • نجاح",
        "dashboard" to "لوحة التحكم",
        "projects" to "المشاريع",
        "attendance" to "الحضور والغياب",
        "tasks" to "المهام",
        "materials" to "المواد",
        "expenses" to "المصروفات",
        "staff" to "فريق العمل",
        "reports" to "التقارير",
        "profile" to "الملف الشخصي",
        "settings" to "الإعدادات",
        "more" to "المزيد",
        "ai_chat" to "مساعد الذكاء الاصطناعي",
        "ai_fill" to "التعبئة التلقائية بالذكاء الاصطناعي",
        "ask_ai" to "اسأل الذكاء الاصطناعي",
        "today_attendance" to "حضور اليوم",
        "ongoing_projects" to "المشاريع الجارية",
        "pending_tasks" to "المهام المعلقة",
        "low_stock" to "تنبيه نقص المواد",
        "project_health" to "حالة المشروع",
        "quick_actions" to "إجراءات سريعة",
        "ai_insights" to "تحليلات الذكاء الاصطناعي",
        "weather_safety" to "طقس الموقع والسلامة",
        "scan_bill" to "مسح الفاتورة ضوئياً",
        "check_in" to "تسجيل دخول",
        "check_out" to "تسجيل خروج",
        "create_project" to "مشروع جديد",
        "add_project" to "إضافة مشروع",
        "create_task" to "مهمة جديدة",
        "add_task" to "إضافة مهمة",
        "add_expense" to "إضافة مصروف",
        "add_material" to "إضافة مواد",
        "add_staff" to "إضافة موظف",
        "generate_report" to "إنشاء تقرير",
        "voice_speak" to "إملاء صوتي",
        "role" to "الدور",
        "language" to "اللغة",
        "budget" to "الميزانية",
        "spent" to "المنفق",
        "progress" to "نسبة الإنجاز",
        "search" to "بحث...",
        "filter" to "تصفية",
        "all" to "الكل",
        "active" to "نشط",
        "planning" to "تخطيط",
        "completed" to "مكتمل",
        "on_hold" to "معلق",
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "edit" to "تعديل",
        "status" to "الحالة",
        "priority" to "الأولوية",
        "present" to "حاضر",
        "absent" to "غائب",
        "half_day" to "نصف يوم",
        "on_leave" to "إجازة",
        "overtime" to "ساعات إضافية",
        "late" to "متأخر",
        "camera_scan" to "مسح بالكاميرا",
        "ai_thinking" to "الذكاء الاصطناعي يفكر...",
        "ai_speaking" to "الذكاء الاصطناعي يتحدث...",
        "auto_speak" to "النطق الصوتي التلقائي",
        "speak_again" to "استمع",
        "stop_speaking" to "إيقاف الصوت",
        "clear_history" to "مسح السجل",
        "voice_input" to "تحدث بأي لغة",
        "quick_questions_title" to "أسئلة فورية للذكاء الاصطناعي",
        "dark_mode" to "الوضع الداكن",
        "ai_suggestions" to "اقتراحات الذكاء الاصطناعي",
        "voice_recognition" to "التعرف على الصوت",
        "reset_data" to "إعادة ضبط البيانات",
        "logout" to "تسجيل خروج"
    )

    private val bengaliMap = mapOf(
        "app_title" to "সাইট ম্যান",
        "tagline" to "ব্যবস্থাপনা • নির্মাণ • সাফল্য",
        "dashboard" to "ড্যাশবোর্ড",
        "projects" to "প্রকল্পসমূহ",
        "attendance" to "উপস্থিতি",
        "tasks" to "কাজ (টাস্ক)",
        "materials" to "উপকরণ (ম্যাটেরিয়াল)",
        "expenses" to "খরচ (ব্যয়)",
        "staff" to "কর্মী (স্টাফ)",
        "reports" to "প্রতিবেদন",
        "profile" to "প্রোফাইল",
        "settings" to "সেটিংস",
        "more" to "আরো",
        "ai_chat" to "এআই সহকারী",
        "ai_fill" to "এআই অটো-ফিল",
        "ask_ai" to "সাইট ম্যান এআই-কে জিজ্ঞাসা করুন",
        "today_attendance" to "আজকের উপস্থিতি",
        "ongoing_projects" to "চলমান প্রকল্পসমূহ",
        "pending_tasks" to "বকেয়া কাজ",
        "low_stock" to "কম স্টকের সতর্কতা",
        "project_health" to "প্রকল্পের স্থিতি",
        "quick_actions" to "দ্রুত অ্যাকশন",
        "ai_insights" to "এআই পরামর্শ ও সতর্কতা",
        "weather_safety" to "আবহাওয়া ও নিরাপত্তা",
        "scan_bill" to "বিল স্ক্যান করুন",
        "check_in" to "চেক ইন",
        "check_out" to "চেক আউট",
        "create_project" to "নতুন প্রকল্প",
        "add_project" to "প্রকল্প যোগ করুন",
        "create_task" to "নতুন কাজ",
        "add_task" to "কাজ যোগ করুন",
        "add_expense" to "খরচ যোগ করুন",
        "add_material" to "ম্যাটেরিয়াল যোগ করুন",
        "add_staff" to "কর্মী যোগ করুন",
        "generate_report" to "রিপোর্ট তৈরি করুন",
        "voice_speak" to "ভয়েসে বলুন",
        "role" to "ভূমিকা",
        "language" to "ভাষা",
        "budget" to "বাজেট",
        "spent" to "খরচ",
        "progress" to "অগ্রগতি",
        "search" to "অনুসন্ধান...",
        "filter" to "ফিল্টার",
        "all" to "সব",
        "active" to "সক্রিয়",
        "planning" to "পরিকল্পনা",
        "completed" to "সম্পন্ন",
        "on_hold" to "স্থগিত",
        "save" to "সংরক্ষণ",
        "cancel" to "বাতিল",
        "delete" to "মুছুন",
        "edit" to "সম্পাদনা",
        "status" to "অবস্থা",
        "priority" to "অগ্রাধিকার",
        "present" to "উপস্থিত",
        "absent" to "অনুপস্থিত",
        "half_day" to "অর্ধ দিবস",
        "on_leave" to "ছুটিতে",
        "overtime" to "ওভারটাইম",
        "late" to "দেরি",
        "camera_scan" to "ক্যামেরা স্ক্যান",
        "ai_thinking" to "এআই চিন্তা করছে...",
        "ai_speaking" to "এআই কথা বলছে...",
        "auto_speak" to "স্বয়ংক্রিয় অডিও",
        "speak_again" to "শুনুন",
        "stop_speaking" to "অডিও থামান",
        "clear_history" to "ইতিহাস মুছুন",
        "voice_input" to "যে কোনো ভাষায় বলুন",
        "quick_questions_title" to "তাত্ক্ষণিক এআই প্রশ্নাবলী",
        "dark_mode" to "ডার্ক মোড",
        "ai_suggestions" to "এআই সাজেশন",
        "voice_recognition" to "ভয়েস স্বীকৃতি",
        "reset_data" to "ডেটা রিসেট",
        "logout" to "লগআউট"
    )

    private val marathiMap = mapOf(
        "app_title" to "साइट मॅन",
        "tagline" to "व्यवस्थापन • बांधकाम • यश",
        "dashboard" to "डॅशबोर्ड",
        "projects" to "प्रकल्प (प्रोजेक्ट्स)",
        "attendance" to "हजेरी (अटेंडन्स)",
        "tasks" to "कामे (टास्क)",
        "materials" to "साहित्य (मटेरियल)",
        "expenses" to "खर्च (एक्सपेन्स)",
        "staff" to "कर्मचारी (स्टाफ)",
        "reports" to "अहवाल (रिपोर्ट्स)",
        "profile" to "प्रोफाइल",
        "settings" to "सेटिंग्ज",
        "more" to "अधिक",
        "ai_chat" to "एआय सहाय्यक",
        "ai_fill" to "एआय ऑटो-फिल",
        "ask_ai" to "साइट मॅन एआय ला विचारा",
        "today_attendance" to "आजची हजेरी",
        "ongoing_projects" to "चालू प्रकल्प",
        "pending_tasks" to "प्रलंबित कामे",
        "low_stock" to "कमी साठा इशारा",
        "project_health" to "प्रकल्प आरोग्य व स्थिती",
        "quick_actions" to "त्वरित कृती",
        "ai_insights" to "एआय सूचना",
        "weather_safety" to "हवामान व सुरक्षा",
        "scan_bill" to "बिल स्कॅन करा",
        "check_in" to "चेक इन",
        "check_out" to "चेक आउट",
        "create_project" to "नवीन प्रकल्प",
        "add_project" to "प्रकल्प जोडा",
        "create_task" to "नवीन काम",
        "add_task" to "काम जोडा",
        "add_expense" to "खर्च जोडा",
        "add_material" to "मटेरियल जोडा",
        "add_staff" to "कर्मचारी जोडा",
        "generate_report" to "अहवाल तयार करा",
        "voice_speak" to "बोलून नोंदवा",
        "role" to "भूमिका",
        "language" to "भाषा",
        "budget" to "बजेट",
        "spent" to "झालेला खर्च",
        "progress" to "प्रगती",
        "search" to "शोधा...",
        "filter" to "फिल्टर",
        "all" to "सर्व",
        "active" to "सक्रिय",
        "planning" to "नियोजन",
        "completed" to "पूर्ण",
        "on_hold" to "थांबवले",
        "save" to "जतन करा",
        "cancel" to "रद्द करा",
        "delete" to "हटवा",
        "edit" to "संपादित करा",
        "status" to "स्थिती",
        "priority" to "प्राधान्य",
        "present" to "हजर",
        "absent" to "गैरहजर",
        "half_day" to "अर्धा दिवस",
        "on_leave" to "रजेवर",
        "overtime" to "ओव्हरटाईम",
        "late" to "उशीरा",
        "camera_scan" to "कॅमेरा स्कॅन",
        "ai_thinking" to "एआय विचार करत आहे...",
        "ai_speaking" to "एआय बोलत आहे...",
        "auto_speak" to "उत्तर आपोआप बोला",
        "speak_again" to "ऐका",
        "stop_speaking" to "आवाज थांबवा",
        "clear_history" to "इतिहास पुसा",
        "voice_input" to "कोणत्याही भाषेत बोला",
        "quick_questions_title" to "त्वरित एआय प्रश्न",
        "dark_mode" to "डार्क मोड",
        "ai_suggestions" to "एआय सूचना",
        "voice_recognition" to "व्हॉईस ओळख",
        "reset_data" to "डेटा रीसेट करा",
        "logout" to "लॉगआउट"
    )

    private val teluguMap = mapOf(
        "app_title" to "సైట్ మ్యాన్",
        "tagline" to "నిర్వహణ • నిర్మాణం • విజయం",
        "dashboard" to "డ్యాష్‌బోర్డ్",
        "projects" to "ప్రాజెక్టులు",
        "attendance" to "హాజరు (అటెండెన్స్)",
        "tasks" to "పనులు (టాస్క్‌లు)",
        "materials" to "మెటీరియల్స్",
        "expenses" to "ఖర్చులు",
        "staff" to "సిబ్బంది",
        "reports" to "రిపోర్టులు",
        "profile" to "ప్రొఫైల్",
        "settings" to "సెట్టింగ్‌లు",
        "more" to "మరిన్ని",
        "ai_chat" to "AI సహాయకుడు",
        "ai_fill" to "AI ఆటో-ఫిల్",
        "ask_ai" to "సైట్ మ్యాన్ AI ని అడగండి",
        "today_attendance" to "నేటి హాజరు",
        "ongoing_projects" to "నడుస్తున్న ప్రాజెక్టులు",
        "pending_tasks" to "పెండింగ్ పనులు",
        "low_stock" to "తక్కువ స్టాక్ హెచ్చరిక",
        "project_health" to "ప్రాజెక్ట్ స్థితి",
        "quick_actions" to "త్వరిత చర్యలు",
        "ai_insights" to "AI సూచనలు",
        "weather_safety" to "వాతావరణం & భద్రత",
        "scan_bill" to "బిల్ స్కాన్ చేయండి",
        "check_in" to "చెక్ ఇన్",
        "check_out" to "చెక్ అవుట్",
        "create_project" to "కొత్త ప్రాజెక్ట్",
        "add_project" to "ప్రాజెక్ట్ జోడించు",
        "create_task" to "కొత్త పని",
        "add_task" to "పనిని జోడించు",
        "add_expense" to "ఖర్చు జోడించు",
        "add_material" to "మెటీరియల్ జోడించు",
        "add_staff" to "సిబ్బందిని జోడించు",
        "generate_report" to "రిపోర్ట్ రూపొందించు",
        "voice_speak" to "వాయిస్ ద్వారా చెప్పండి",
        "role" to "పాత్ర",
        "language" to "భాష",
        "budget" to "బడ్జెట్",
        "spent" to "ఖర్చు చేసినది",
        "progress" to "పురోగతి",
        "search" to "శోధించండి...",
        "filter" to "ఫిల్టర్",
        "all" to "అన్నీ",
        "active" to "యాక్టివ్",
        "planning" to "ప్లానింగ్",
        "completed" to "పూర్తయింది",
        "on_hold" to "నిలిపివేయబడింది",
        "save" to "సేవ్ చేయండి",
        "cancel" to "రద్దు చేయండి",
        "delete" to "తొలగించండి",
        "edit" to "సవరించండి",
        "status" to "స్థితి",
        "priority" to "ప్రాధాన్యత",
        "present" to "హాజరు",
        "absent" to "గైర్హాజరు",
        "half_day" to "సగం రోజు",
        "on_leave" to "సెలవులో",
        "overtime" to "ఓవర్ టైమ్",
        "late" to "ఆలస్యం",
        "camera_scan" to "కెమెరా స్కానర్",
        "ai_thinking" to "AI ఆలోచిస్తోంది...",
        "ai_speaking" to "AI మాట్లాడుతోంది...",
        "auto_speak" to "ఆటోమేటిక్ వాయిస్",
        "speak_again" to "వినండి",
        "stop_speaking" to "వాయిస్ ఆపు",
        "clear_history" to "చరిత్రను తొలగించు",
        "voice_input" to "ఏ భాషలోనైనా మాట్లాడండి",
        "quick_questions_title" to "త్వరిత AI ప్రశ్నలు",
        "dark_mode" to "డార్క్ మోడ్",
        "ai_suggestions" to "AI సూచనలు",
        "voice_recognition" to "వాయిస్ గుర్తింపు",
        "reset_data" to "డేటా రీసెట్",
        "logout" to "లాగ్ అవుట్"
    )

    private val tamilMap = mapOf(
        "app_title" to "சைட் மேன்",
        "tagline" to "நிர்வாகம் • கட்டுமானம் • வெற்றி",
        "dashboard" to "டாஷ்போர்டு",
        "projects" to "திட்டங்கள்",
        "attendance" to "வருகைப்பதிவு",
        "tasks" to "பணிகள் (டாஸ்க்)",
        "materials" to "பொருட்கள்",
        "expenses" to "செலவுகள்",
        "staff" to "பணியாளர்கள்",
        "reports" to "அறிக்கைகள்",
        "profile" to "சுயவிவரம்",
        "settings" to "அமைப்புகள்",
        "more" to "மேலும்",
        "ai_chat" to "AI உதவியாளர்",
        "ai_fill" to "AI தானியங்கி நிரப்புதல்",
        "ask_ai" to "சைட் மேன் AI-யிடம் கேளுங்கள்",
        "today_attendance" to "இன்றைய வருகை",
        "ongoing_projects" to "நடப்பு திட்டங்கள்",
        "pending_tasks" to "நிலுவையில் உள்ள பணிகள்",
        "low_stock" to "குறைந்த இருப்பு எச்சரிக்கை",
        "project_health" to "திட்டத்தின் நிலை",
        "quick_actions" to "விரைவு நடவடிக்கைகள்",
        "ai_insights" to "AI நுண்ணறிவுகள்",
        "weather_safety" to "வானிலை மற்றும் பாதுகாப்பு",
        "scan_bill" to "ரசீது ஸ்கேன் செய்",
        "check_in" to "வருகை பதிவு",
        "check_out" to "வெளியேறுதல் பதிவு",
        "create_project" to "புதிய திட்டம்",
        "add_project" to "திட்டம் சேர்",
        "create_task" to "புதிய பணி",
        "add_task" to "பணி சேர்",
        "add_expense" to "செலவு சேர்",
        "add_material" to "பொருள் சேர்",
        "add_staff" to "பணியாளர் சேர்",
        "generate_report" to "அறிக்கை உருவாக்கு",
        "voice_speak" to "குரல் மூலம் பேசு",
        "role" to "பங்கு",
        "language" to "மொழி",
        "budget" to "பட்ஜெட்",
        "spent" to "செலவிடப்பட்டது",
        "progress" to "முன்னேற்றம்",
        "search" to "தேடு...",
        "filter" to "வடிகட்டு",
        "all" to "அனைத்தும்",
        "active" to "செயலில்",
        "planning" to "திட்டமிடல்",
        "completed" to "முடிந்தது",
        "on_hold" to "நிறுத்தி வைக்கப்பட்டது",
        "save" to "சேமி",
        "cancel" to "ரத்து செய்",
        "delete" to "நீக்கு",
        "edit" to "திருத்து",
        "status" to "நிலை",
        "priority" to "முன்னுரிமை",
        "present" to "வருகை",
        "absent" to "வராதவர்",
        "half_day" to "அரை நாள்",
        "on_leave" to "விடுப்பு",
        "overtime" to "கூடுதல் நேரம்",
        "late" to "தாமதம்",
        "camera_scan" to "கேமரா ஸ்கேன்",
        "ai_thinking" to "AI சிந்திக்கிறது...",
        "ai_speaking" to "AI பேசுகிறது...",
        "auto_speak" to "தானியங்கி குரல்",
        "speak_again" to "கேளுங்கள்",
        "stop_speaking" to "குரலை நிறுத்து",
        "clear_history" to "வரலாற்றை அழி",
        "voice_input" to "எந்த மொழியிலும் பேசுங்கள்",
        "quick_questions_title" to "விரைவு AI கேள்விகள்",
        "dark_mode" to "டார்க் மோட்",
        "ai_suggestions" to "AI பரிந்துரைகள்",
        "voice_recognition" to "குரல் அறிதல்",
        "reset_data" to "தரவை மீட்டமை",
        "logout" to "வெளியேறு"
    )

    private val gujaratiMap = mapOf(
        "app_title" to "સાઇટ મેન",
        "tagline" to "સંચાલન • નિર્માણ • સફળતા",
        "dashboard" to "ડેશબોર્ડ",
        "projects" to "પ્રોજેક્ટ્સ",
        "attendance" to "હાજરી",
        "tasks" to "કાર્યો (ટાસ્ક)",
        "materials" to "સામગ્રી",
        "expenses" to "ખર્ચાઓ",
        "staff" to "સ્ટાફ",
        "reports" to "અહેવાલો",
        "profile" to "પ્રોફાઇલ",
        "settings" to "સેટિંગ્સ",
        "more" to "વધુ",
        "ai_chat" to "AI સહાયક",
        "ai_fill" to "AI ઓટો-ફિલ",
        "ask_ai" to "સાઇટ મેન AI ને પૂછો",
        "today_attendance" to "આજની હાજરી",
        "ongoing_projects" to "ચાલુ પ્રોજેક્ટ્સ",
        "pending_tasks" to "બાકી કાર્યો",
        "low_stock" to "ઓછો સ્ટોક ચેતવણી",
        "project_health" to "પ્રોજેક્ટ સ્થિતિ",
        "quick_actions" to "ઝડપી ક્રિયાઓ",
        "ai_insights" to "AI સૂચનો",
        "weather_safety" to "હવામાન અને સુરક્ષા",
        "scan_bill" to "બિલ સ્કેન કરો",
        "check_in" to "ચેક ઇન",
        "check_out" to "ચેક આઉટ",
        "create_project" to "નવો પ્રોજેક્ટ",
        "add_project" to "પ્રોજેક્ટ ઉમેરો",
        "create_task" to "નવું કાર્ય",
        "add_task" to "કાર્ય ઉમેરો",
        "add_expense" to "ખર્ચ ઉમેરો",
        "add_material" to "સામગ્રી ઉમેરો",
        "add_staff" to "સ્ટાફ ઉમેરો",
        "generate_report" to "અહેવાલ બનાવો",
        "voice_speak" to "બોલીને નોંધો",
        "role" to "ભૂમિકા",
        "language" to "ભાષા",
        "budget" to "બજેટ",
        "spent" to "ખર્ચાયેલ",
        "progress" to "પ્રગતિ",
        "search" to "શોધો...",
        "filter" to "ફિલ્ટર",
        "all" to "બધા",
        "active" to "સક્રિય",
        "planning" to "આયોજન",
        "completed" to "પૂર્ણ",
        "on_hold" to "સ્થગિત",
        "save" to "સાચવો",
        "cancel" to "રદ કરો",
        "delete" to "કાઢી નાખો",
        "edit" to "સંપાદિત કરો",
        "status" to "સ્થિતિ",
        "priority" to "પ્રાથમિકતા",
        "present" to "હાજર",
        "absent" to "ગેરહાજર",
        "half_day" to "અડધો દિવસ",
        "on_leave" to "રજા પર",
        "overtime" to "ઓવરટાઇમ",
        "late" to "મોડું",
        "camera_scan" to "કેમેરા સ્કેન",
        "ai_thinking" to "AI વિચારી રહ્યું છે...",
        "ai_speaking" to "AI બોલી રહ્યું છે...",
        "auto_speak" to "સ્વચાલિત અવાજ",
        "speak_again" to "સાંભળો",
        "stop_speaking" to "અવાજ બંધ કરો",
        "clear_history" to "ઇતિહાસ સાફ કરો",
        "voice_input" to "કોઈપણ ભાષામાં બોલો",
        "quick_questions_title" to "ઝડપી AI પ્રશ્નો",
        "dark_mode" to "ડાર્ક મોડ",
        "ai_suggestions" to "AI સૂચનો",
        "voice_recognition" to "અવાજ ઓળખ",
        "reset_data" to "ડેટા રીસેટ",
        "logout" to "લૉગઆઉટ"
    )

    private val kannadaMap = mapOf(
        "app_title" to "ಸೈಟ್ ಮ್ಯಾನ್",
        "tagline" to "ನಿರ್ವಹಣೆ • ನಿರ್ಮಾಣ • ಯಶಸ್ಸು",
        "dashboard" to "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "projects" to "ಯೋಜನೆಗಳು",
        "attendance" to "ಹಾಜರಾತಿ",
        "tasks" to "ಕಾರ್ಯಗಳು",
        "materials" to "ಸಾಮಗ್ರಿಗಳು",
        "expenses" to "ವೆಚ್ಚಗಳು",
        "staff" to "ಸಿಬ್ಬಂದಿ",
        "reports" to "ವರದಿಗಳು",
        "profile" to "ಪ್ರೊಫೈಲ್",
        "settings" to "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "more" to "ಇನ್ನಷ್ಟು",
        "ai_chat" to "AI ಸಹಾಯಕ",
        "ai_fill" to "AI ಸ್ವಯಂ ಭರ್ತಿ",
        "ask_ai" to "ಸೈಟ್ ಮ್ಯಾನ್ AI ಕೇಳಿ",
        "today_attendance" to "ಇಂದಿನ ಹಾಜರಾತಿ",
        "ongoing_projects" to "ಪ್ರಸ್ತುತ ಯೋಜನೆಗಳು",
        "pending_tasks" to "ಬಾಕಿ ಕಾರ್ಯಗಳು",
        "low_stock" to "ಕಡಿಮೆ ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆ",
        "project_health" to "ಯೋಜನೆ ಸ್ಥಿತಿ",
        "quick_actions" to "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
        "ai_insights" to "AI ಒಳನೋಟಗಳು",
        "weather_safety" to "ಹವಾಮಾನ ಮತ್ತು ಸುರಕ್ಷತೆ",
        "scan_bill" to "ಬಿಲ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "check_in" to "ಚೆಕ್ ಇನ್",
        "check_out" to "ಚೆಕ್ ಔಟ್",
        "create_project" to "ಹೊಸ ಯೋಜನೆ",
        "add_project" to "ಯೋಜನೆ ಸೇರಿಸಿ",
        "create_task" to "ಹೊಸ ಕಾರ್ಯ",
        "add_task" to "ಕಾರ್ಯ ಸೇರಿಸಿ",
        "add_expense" to "ವೆಚ್ಚ ಸೇರಿಸಿ",
        "add_material" to "ಸಾಮಗ್ರಿ ಸೇರಿಸಿ",
        "add_staff" to "ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ",
        "generate_report" to "ವರದಿ ರಚಿಸಿ",
        "voice_speak" to "ಧ್ವನಿ ಮೂಲಕ ಹೇಳಿ",
        "role" to "ಪಾತ್ರ",
        "language" to "ಭಾಷೆ",
        "budget" to "ಬಜೆಟ್",
        "spent" to "ಖರ್ಚು ಮಾಡಿದ್ದು",
        "progress" to "ಪ್ರಗತಿ",
        "search" to "ಹುಡುಕಿ...",
        "filter" to "ಫಿಲ್ಟರ್",
        "all" to "ಎಲ್ಲಾ",
        "active" to "ಸಕ್ರಿಯ",
        "planning" to "ಯೋಜನೆ",
        "completed" to "ಪೂರ್ಣಗೊಂಡಿದೆ",
        "on_hold" to "ತಡೆಹಿಡಿಯಲಾಗಿದೆ",
        "save" to "ಉಳಿಸಿ",
        "cancel" to "ರದ್ದುಮಾಡಿ",
        "delete" to "ಅಳಿಸಿ",
        "edit" to "ತಿದ್ದು",
        "status" to "ಸ್ಥಿತಿ",
        "priority" to "ಆದ್ಯತೆ",
        "present" to "ಹಾಜರು",
        "absent" to "ಗೈರುಹಾಜರು",
        "half_day" to "ಅರ್ಧ ದಿನ",
        "on_leave" to "ರಜೆಯಲ್ಲಿದ್ದಾರೆ",
        "overtime" to "ಹೆಚ್ಚುವರಿ ಸಮಯ",
        "late" to "ತಡವಾಗಿ",
        "camera_scan" to "ಕ್ಯಾಮೆರಾ ಸ್ಕ್ಯಾನ್",
        "ai_thinking" to "AI ಯೋಚಿಸುತ್ತಿದೆ...",
        "ai_speaking" to "AI ಮಾತನಾಡುತ್ತಿದೆ...",
        "auto_speak" to "ಸ್ವಯಂ ಧ್ವನಿ",
        "speak_again" to "ಕೇಳಿ",
        "stop_speaking" to "ಧ್ವನಿ ನಿಲ್ಲಿಸಿ",
        "clear_history" to "ಇತಿಹಾಸ ಅಳಿಸಿ",
        "voice_input" to "ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
        "quick_questions_title" to "ತ್ವರಿತ AI ಪ್ರಶ್ನೆಗಳು",
        "dark_mode" to "ಡಾರ್ಕ್ ಮೋಡ್",
        "ai_suggestions" to "AI ಸಲಹೆಗಳು",
        "voice_recognition" to "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ",
        "reset_data" to "ಡೇಟಾ ಮರುಹೊಂದಿಸಿ",
        "logout" to "ಲಾಗ್ ಔಟ್"
    )

    private val punjabiMap = mapOf(
        "app_title" to "ਸਾਈਟ ਮੈਨ",
        "tagline" to "ਪ੍ਰਬੰਧਨ • ਨਿਰਮਾਣ • ਸਫਲਤਾ",
        "dashboard" to "ਡੈਸ਼ਬੋਰਡ",
        "projects" to "ਪ੍ਰੋਜੈਕਟ",
        "attendance" to "ਹਾਜ਼ਰੀ",
        "tasks" to "ਕੰਮ (ਟਾਸਕ)",
        "materials" to "ਸਮੱਗਰੀ",
        "expenses" to "ਖਰਚੇ",
        "staff" to "ਸਟਾਫ",
        "reports" to "ਰਿਪੋਰਟਾਂ",
        "profile" to "ਪ੍ਰੋਫਾਈਲ",
        "settings" to "ਸੈਟਿੰਗਾਂ",
        "more" to "ਹੋਰ",
        "ai_chat" to "AI ਸਹਾਇਕ",
        "ai_fill" to "AI ਆਟੋ-ਭਰੋ",
        "ask_ai" to "ਸਾਈਟ ਮੈਨ AI ਨੂੰ ਪੁੱਛੋ",
        "today_attendance" to "ਅੱਜ ਦੀ ਹਾਜ਼ਰੀ",
        "ongoing_projects" to "ਚੱਲ ਰਹੇ ਪ੍ਰੋਜੈਕਟ",
        "pending_tasks" to "ਬਾਕੀ ਕੰਮ",
        "low_stock" to "ਘੱਟ ਸਟਾਕ ਚੇਤਾਵਨੀ",
        "project_health" to "ਪ੍ਰੋਜੈਕਟ ਸਥਿਤੀ",
        "quick_actions" to "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
        "ai_insights" to "AI ਸੁਝਾਅ",
        "weather_safety" to "ਮੌਸਮ ਅਤੇ ਸੁਰੱਖਿਆ",
        "scan_bill" to "ਬਿੱਲ ਸਕੈਨ ਕਰੋ",
        "check_in" to "ਚੈੱਕ ਇਨ",
        "check_out" to "ਚੈੱਕ ਆਊਟ",
        "create_project" to "ਨਵਾਂ ਪ੍ਰੋਜੈਕਟ",
        "add_project" to "ਪ੍ਰੋਜੈਕਟ ਜੋੜੋ",
        "create_task" to "ਨਵਾਂ ਕੰਮ",
        "add_task" to "ਕੰਮ ਜੋੜੋ",
        "add_expense" to "ਖਰਚਾ ਜੋੜੋ",
        "add_material" to "ਸਮੱਗਰੀ ਜੋੜੋ",
        "add_staff" to "ਸਟਾਫ ਜੋੜੋ",
        "generate_report" to "ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ",
        "voice_speak" to "ਬੋਲ ਕੇ ਦਰਜ ਕਰੋ",
        "role" to "ਭੂਮਿਕਾ",
        "language" to "ਭਾਸ਼ਾ",
        "budget" to "ਬਜਟ",
        "spent" to "ਖਰਚਿਆ",
        "progress" to "ਤਰੱਕੀ",
        "search" to "ਖੋਜੋ...",
        "filter" to "ਫਿਲਟਰ",
        "all" to "ਸਾਰੇ",
        "active" to "ਸਰਗਰਮ",
        "planning" to "ਯੋਜਨਾਬੰਦੀ",
        "completed" to "ਪੂਰਾ ਹੋਇਆ",
        "on_hold" to "ਰੋਕਿਆ ਹੋਇਆ",
        "save" to "ਸੰਭਾਲੋ",
        "cancel" to "ਰੱਦ ਕਰੋ",
        "delete" to "ਮਿਟਾਓ",
        "edit" to "ਸੰਪਾਦਿਤ ਕਰੋ",
        "status" to "ਸਥਿਤੀ",
        "priority" to "ਤਰਜੀਹ",
        "present" to "ਹਾਜ਼ਰ",
        "absent" to "ਗੈਰਹਾਜ਼ਰ",
        "half_day" to "ਅੱਧਾ ਦਿਨ",
        "on_leave" to "ਛੁੱਟੀ 'ਤੇ",
        "overtime" to "ਓਵਰਟਾਈਮ",
        "late" to "ਦੇਰ",
        "camera_scan" to "ਕੈਮਰਾ ਸਕੈਨ",
        "ai_thinking" to "AI ਸੋਚ ਰਿਹਾ ਹੈ...",
        "ai_speaking" to "AI ਬੋਲ ਰਿਹਾ ਹੈ...",
        "auto_speak" to "ਆਟੋ-ਬੋਲੋ",
        "speak_again" to "ਸੁਣੋ",
        "stop_speaking" to "ਆਵਾਜ਼ ਰੋਕੋ",
        "clear_history" to "ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ",
        "voice_input" to "ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ",
        "quick_questions_title" to "ਤੁਰੰਤ AI ਸਵਾਲ",
        "dark_mode" to "ਡਾਰਕ ਮੋਡ",
        "ai_suggestions" to "AI ਸੁਝਾਅ",
        "voice_recognition" to "ਆਵਾਜ਼ ਪਛਾਣ",
        "reset_data" to "ਡੇਟਾ ਰੀਸੈੱਟ ਕਰੋ",
        "logout" to "ਲਾਗਆਉਟ"
    )

    private val malayalamMap = mapOf(
        "app_title" to "സൈറ്റ് മാൻ",
        "tagline" to "മാനേജ്മെന്റ് • നിർമ്മാണം • വിജയം",
        "dashboard" to "ഡാഷ്‌ബോർഡ്",
        "projects" to "പ്രോജക്റ്റുകൾ",
        "attendance" to "ഹാജർ",
        "tasks" to "ടാസ്ക്കുകൾ",
        "materials" to "സാമഗ്രികൾ",
        "expenses" to "ചെലവുകൾ",
        "staff" to "ജീവനക്കാർ",
        "reports" to "റിപ്പോർട്ടുകൾ",
        "profile" to "പ്രൊഫൈൽ",
        "settings" to "ക്രമീകരണങ്ങൾ",
        "more" to "കൂടുതൽ",
        "ai_chat" to "AI അസിസ്റ്റന്റ്",
        "ai_fill" to "AI ഓട്ടോ-ഫിൽ",
        "ask_ai" to "സൈറ്റ് മാൻ AI ചോദിക്കുക",
        "today_attendance" to "ഇന്നത്തെ ഹാജർ",
        "ongoing_projects" to "നടന്നുകൊണ്ടിരിക്കുന്ന പ്രോജക്റ്റുകൾ",
        "pending_tasks" to "തീർപ്പാക്കാത്ത ജോലികൾ",
        "low_stock" to "സ്റ്റോക്ക് കുറവ് മുന്നറിയിപ്പ്",
        "project_health" to "പ്രോജക്റ്റ് നില",
        "quick_actions" to "ദ്രുത പ്രവർത്തനങ്ങൾ",
        "ai_insights" to "AI ഉൾക്കാഴ്ചകൾ",
        "weather_safety" to "കാലാവസ്ഥയും സുരക്ഷയും",
        "scan_bill" to "ബിൽ സ്കാൻ ചെയ്യുക",
        "check_in" to "ചെക്ക് ഇൻ",
        "check_out" to "ചെക്ക് ഔട്ട്",
        "create_project" to "പുതിയ പ്രോജക്റ്റ്",
        "add_project" to "പ്രോജക്റ്റ് ചേർക്കുക",
        "create_task" to "പുതിയ ടാസ്ക്",
        "add_task" to "ടാസ്ക് ചേർക്കുക",
        "add_expense" to "ചെലവ് ചേർക്കുക",
        "add_material" to "സാമഗ്രി ചേർക്കുക",
        "add_staff" to "ജീവനക്കാരെ ചേർക്കുക",
        "generate_report" to "റിപ്പോർട്ട് സൃഷ്ടിക്കുക",
        "voice_speak" to "ശബ്ദത്തിലൂടെ പറയുക",
        "role" to "റോൾ",
        "language" to "ഭാഷ",
        "budget" to "ബജറ്റ്",
        "spent" to "ചെലവഴിച്ചത്",
        "progress" to "പുരോഗതി",
        "search" to "തിരയുക...",
        "filter" to "ഫിൽട്ടർ",
        "all" to "എല്ലാം",
        "active" to "സജീവം",
        "planning" to "ആസൂത്രണം",
        "completed" to "പൂർത്തിയായി",
        "on_hold" to "നിർത്തിവച്ചു",
        "save" to "സംരക്ഷിക്കുക",
        "cancel" to "റദ്ദാക്കുക",
        "delete" to "ഇല്ലാതാക്കുക",
        "edit" to "തിരുത്തുക",
        "status" to "നില",
        "priority" to "മുൻഗണന",
        "present" to "ഹാജർ",
        "absent" to "ഹാജരല്ല",
        "half_day" to "അര ദിവസം",
        "on_leave" to "അവധിയിൽ",
        "overtime" to "ഓവർടൈം",
        "late" to "വൈകി",
        "camera_scan" to "ക്യാമറ സ്കാൻ",
        "ai_thinking" to "AI ചിന്തിക്കുന്നു...",
        "ai_speaking" to "AI സംസാരിക്കുന്നു...",
        "auto_speak" to "ഓട്ടോ-വോയ്സ്",
        "speak_again" to "കേൾക്കുക",
        "stop_speaking" to "ഓഡിയോ നിർത്തുക",
        "clear_history" to "ചരിത്രം മായ്‌ക്കുക",
        "voice_input" to "ഏത് ഭാഷയിലും സംസാരിക്കുക",
        "quick_questions_title" to "തൽക്ഷണ AI ചോദ്യങ്ങൾ",
        "dark_mode" to "ഡാർക്ക് മോഡ്",
        "ai_suggestions" to "AI നിർദ്ദേശങ്ങൾ",
        "voice_recognition" to "ശബ്ദം തിരിച്ചറിയൽ",
        "reset_data" to "ഡാറ്റ പുനഃസജ്ജമാക്കുക",
        "logout" to "ലോഗൗട്ട്"
    )

    private val odiaMap = mapOf(
        "app_title" to "ସାଇଟ୍ ମ୍ୟାନ୍",
        "tagline" to "ପରିଚାଳନା • ନିର୍ମାଣ • ସଫଳତା",
        "dashboard" to "ଡ୍ୟାସବୋର୍ଡ",
        "projects" to "ପ୍ରକଳ୍ପ",
        "attendance" to "ଉପସ୍ଥିତି",
        "tasks" to "କାର୍ଯ୍ୟ",
        "materials" to "ସାମଗ୍ରୀ",
        "expenses" to "ଖର୍ଚ୍ଚ",
        "staff" to "କର୍ମଚାରୀ",
        "reports" to "ରିପୋର୍ଟ",
        "profile" to "ପ୍ରୋଫାଇଲ",
        "settings" to "ସେଟିଂସ",
        "more" to "ଅଧିକ",
        "ai_chat" to "AI ସହାୟକ",
        "ai_fill" to "AI ସ୍ୱୟଂ ପୂରଣ",
        "ask_ai" to "ସାଇଟ୍ ମ୍ୟାନ୍ AI କୁ ପଚାରନ୍ତୁ",
        "today_attendance" to "ଆଜିର ଉପସ୍ଥିତି",
        "ongoing_projects" to "ଚାଲୁଥିବା ପ୍ରକଳ୍ପ",
        "pending_tasks" to "ବାକି ଥିବା କାର୍ଯ୍ୟ",
        "low_stock" to "କମ୍ ଷ୍ଟକ୍ ଚେତାବନୀ",
        "project_health" to "ପ୍ରକଳ୍ପ ସ୍ଥିତି",
        "quick_actions" to "ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
        "ai_insights" to "AI ପରାମର୍ଶ",
        "weather_safety" to "ପାଣିପାଗ ଏବଂ ସୁରକ୍ଷା",
        "scan_bill" to "ବିଲ୍ ସ୍କାନ୍ କରନ୍ତୁ",
        "check_in" to "ଚେକ୍ ଇନ୍",
        "check_out" to "ଚେକ୍ ଆଉଟ୍",
        "create_project" to "ନୂଆ ପ୍ରକଳ୍ପ",
        "add_project" to "ପ୍ରକଳ୍ପ ଯୋଡନ୍ତୁ",
        "create_task" to "ନୂଆ କାର୍ଯ୍ୟ",
        "add_task" to "କାର୍ଯ୍ୟ ଯୋଡନ୍ତୁ",
        "add_expense" to "ଖର୍ଚ୍ଚ ଯୋଡନ୍ତୁ",
        "add_material" to "ସାମଗ୍ରୀ ଯୋଡନ୍ତୁ",
        "add_staff" to "କର୍ମଚାରୀ ଯୋଡନ୍ତୁ",
        "generate_report" to "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
        "voice_speak" to "ସ୍ୱରରେ କୁହନ୍ତୁ",
        "role" to "ଭୂମିକା",
        "language" to "ଭାଷା",
        "budget" to "ବଜେଟ୍",
        "spent" to "ଖର୍ଚ୍ଚ ହୋଇଥିବା",
        "progress" to "ପ୍ରଗତି",
        "search" to "ଖୋଜନ୍ତୁ...",
        "filter" to "ଫିଲ୍ଟର୍",
        "all" to "ସମସ୍ତ",
        "active" to "ସକ୍ରିୟ",
        "planning" to "ଯୋଜନା",
        "completed" to "ସମ୍ପୂର୍ଣ୍ଣ",
        "on_hold" to "ସ୍ଥଗିତ",
        "save" to "ସାଇତନ୍ତୁ",
        "cancel" to "ବାତିଲ୍",
        "delete" to "ଡିଲିଟ୍",
        "edit" to "ସମ୍ପାଦନ",
        "status" to "ସ୍ଥିତି",
        "priority" to "ପ୍ରାଥମିକତା",
        "present" to "ଉପସ୍ଥିତ",
        "absent" to "ଅନୁପସ୍ଥିତ",
        "half_day" to "ଅଧା ଦିନ",
        "on_leave" to "ଛୁଟିରେ",
        "overtime" to "ଅତିରିକ୍ତ ସମୟ",
        "late" to "ବିଳମ୍ବ",
        "camera_scan" to "କ୍ୟାମେରା ସ୍କାନ୍",
        "ai_thinking" to "AI ଭାବୁଛି...",
        "ai_speaking" to "AI କହୁଛି...",
        "auto_speak" to "ସ୍ୱୟଂଚାଳିତ ସ୍ୱର",
        "speak_again" to "ଶୁଣନ୍ତୁ",
        "stop_speaking" to "ଅଡିଓ ବନ୍ଦ କରନ୍ତୁ",
        "clear_history" to "ଇତିହାସ ସଫା କରନ୍ତୁ",
        "voice_input" to "ଯେକୌଣସି ଭାଷାରେ କୁହନ୍ତୁ",
        "quick_questions_title" to "ତତକ୍ଷଣାତ୍ AI ପ୍ରଶ୍ନ",
        "dark_mode" to "ଡାର୍କ ମୋଡ୍",
        "ai_suggestions" to "AI ପରାମର୍ଶ",
        "voice_recognition" to "ସ୍ୱର ଚିହ୍ନଟ",
        "reset_data" to "ଡାଟା ପୁନଃସେଟ୍",
        "logout" to "ଲଗ୍ ଆଉଟ୍"
    )

    private val urduMap = mapOf(
        "app_title" to "سائٹ مین",
        "tagline" to "انتظام • تعمیر • کامیابی",
        "dashboard" to "ڈیش بورڈ",
        "projects" to "منصوبے",
        "attendance" to "حاضری",
        "tasks" to "کام (ٹاسک)",
        "materials" to "تعمیراتی سامان",
        "expenses" to "اخراجات",
        "staff" to "عملہ (اسٹاف)",
        "reports" to "رپورٹس",
        "profile" to "پروفائل",
        "settings" to "ترتیبات",
        "more" to "مزید",
        "ai_chat" to "اے آئی معاون",
        "ai_fill" to "اے آئی آٹو فل",
        "ask_ai" to "سائٹ مین اے آئی سے پوچھیں",
        "today_attendance" to "آج کی حاضری",
        "ongoing_projects" to "جاری منصوبے",
        "pending_tasks" to "زیر التواء کام",
        "low_stock" to "کم اسٹاک کا انتباہ",
        "project_health" to "منصوبے کی حالت",
        "quick_actions" to "فوری اقدامات",
        "ai_insights" to "اے آئی تجاویز",
        "weather_safety" to "موسم اور حفاظت",
        "scan_bill" to "بل اسکین کریں",
        "check_in" to "آمد درج کریں",
        "check_out" to "روانگی درج کریں",
        "create_project" to "نیا منصوبہ",
        "add_project" to "منصوبہ شامل کریں",
        "create_task" to "نیا کام",
        "add_task" to "کام شامل کریں",
        "add_expense" to "خرچہ درج کریں",
        "add_material" to "سامان شامل کریں",
        "add_staff" to "عملہ شامل کریں",
        "generate_report" to "رپورٹ بنائیں",
        "voice_speak" to "بول کر درج کریں",
        "role" to "کردار",
        "language" to "زبان",
        "budget" to "بجٹ",
        "spent" to "خرچ شدہ",
        "progress" to "پیش رفت",
        "search" to "تلاش کریں...",
        "filter" to "فلٹر",
        "all" to "تمام",
        "active" to "فعال",
        "planning" to "منصوبہ بندی",
        "completed" to "مکمل",
        "on_hold" to "معطل",
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "delete" to "حذف کریں",
        "edit" to "ترمیم کریں",
        "status" to "حیثیت",
        "priority" to "ترجیح",
        "present" to "حاضر",
        "absent" to "غیر حاضر",
        "half_day" to "نصف دن",
        "on_leave" to "رخصت پر",
        "overtime" to "اضافی وقت",
        "late" to "تاخیر",
        "camera_scan" to "کیمرہ اسکین",
        "ai_thinking" to "اے آئی سوچ رہا ہے...",
        "ai_speaking" to "اے آئی بول رہا ہے...",
        "auto_speak" to "خودکار آواز",
        "speak_again" to "سنیں",
        "stop_speaking" to "آواز روکیں",
        "clear_history" to "تاریخ صاف کریں",
        "voice_input" to "کسی بھی زبان میں بولیں",
        "quick_questions_title" to "فوری اے آئی سوالات",
        "dark_mode" to "ڈارک موڈ",
        "ai_suggestions" to "اے آئی تجاویز",
        "voice_recognition" to "آواز کی شناخت",
        "reset_data" to "ڈیٹا ری سیٹ کریں",
        "logout" to "لاگ آؤٹ"
    )

    private val bhojpuriMap = mapOf(
        "app_title" to "साइट मैन",
        "tagline" to "प्रबंधन • निर्माण • सफलता",
        "dashboard" to "डैशबोर्ड",
        "projects" to "प्रोजेक्ट सब",
        "attendance" to "हाजिरी",
        "tasks" to "काम (टास्क)",
        "materials" to "सामान (मटेरियल)",
        "expenses" to "खर्चा",
        "staff" to "कर्मचारी",
        "reports" to "रिपोर्ट",
        "profile" to "प्रोफाइल",
        "settings" to "सेटिंग्स",
        "more" to "और सब",
        "ai_chat" to "एआई सहेली/सहायक",
        "ai_fill" to "एआई ऑटो-भरल",
        "ask_ai" to "एआई से पूछीं",
        "today_attendance" to "आज के हाजिरी",
        "ongoing_projects" to "चलत प्रोजेक्ट",
        "pending_tasks" to "बाकी काम",
        "low_stock" to "सामान कम बा",
        "project_health" to "प्रोजेक्ट के हाल",
        "quick_actions" to "जल्दी के काम",
        "ai_insights" to "एआई सलाह",
        "weather_safety" to "मौसम अउर सुरक्षा",
        "scan_bill" to "बिल स्कैन करीं",
        "check_in" to "हाजिरी लगाईं",
        "check_out" to "छुट्टी दर्ज करीं",
        "create_project" to "नया प्रोजेक्ट",
        "add_project" to "प्रोजेक्ट जोड़ीं",
        "create_task" to "नया काम",
        "add_task" to "काम जोड़ीं",
        "add_expense" to "खर्चा जोड़ीं",
        "add_material" to "सामान जोड़ीं",
        "add_staff" to "मजदूर/स्टाफ जोड़ीं",
        "generate_report" to "रिपोर्ट बनाईं",
        "voice_speak" to "बोल के भरीं",
        "role" to "पद",
        "language" to "भाषा",
        "budget" to "बजट",
        "spent" to "लागल पईसा",
        "progress" to "काम कतना भइल",
        "search" to "खोजीं...",
        "filter" to "छांटीं",
        "all" to "कुल",
        "active" to "चालू",
        "planning" to "प्लानिंग",
        "completed" to "पूरा भइल",
        "on_hold" to "रुकावल",
        "save" to "सेव करीं",
        "cancel" to "रद्द करीं",
        "delete" to "हटाईं",
        "edit" to "सुधारीं",
        "status" to "हाल",
        "priority" to "जरूरी",
        "present" to "आइल बा",
        "absent" to "नाहीं आइल",
        "half_day" to "आधा दिन",
        "on_leave" to "छुट्टी पर",
        "overtime" to "ओवरटाइम",
        "late" to "देर भइल",
        "camera_scan" to "कैमरा से स्कैन",
        "ai_thinking" to "एआई सोचत बा...",
        "ai_speaking" to "एआई बोलत बा...",
        "auto_speak" to "अपने आप बोली",
        "speak_again" to "सुनीं",
        "stop_speaking" to "आवाज रोकीं",
        "clear_history" to "इतिहास मेटाईं",
        "voice_input" to "कवनो भाखा में बोलीं",
        "quick_questions_title" to "झटपट एआई सवाल",
        "dark_mode" to "डार्क मोड",
        "ai_suggestions" to "एआई सुझाव",
        "voice_recognition" to "आवाज पहचान",
        "reset_data" to "डेटा साफ करीं",
        "logout" to "बाहर निकलीं"
    )

    private val portugueseMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Gerenciar • Construir • Vencer",
        "dashboard" to "Painel",
        "projects" to "Projetos",
        "attendance" to "Frequência",
        "tasks" to "Tarefas",
        "materials" to "Materiais",
        "expenses" to "Despesas",
        "staff" to "Equipe",
        "reports" to "Relatórios",
        "profile" to "Perfil",
        "settings" to "Configurações",
        "more" to "Mais",
        "ai_chat" to "Assistente IA",
        "ai_fill" to "Auto-preenchimento IA",
        "ask_ai" to "Perguntar à IA",
        "today_attendance" to "Presença de Hoje",
        "ongoing_projects" to "Projetos em Andamento",
        "pending_tasks" to "Tarefas Pendentes",
        "low_stock" to "Alerta de Estoque Baixo",
        "project_health" to "Saúde da Obra",
        "quick_actions" to "Ações Rápidas",
        "ai_insights" to "Recomendações IA",
        "weather_safety" to "Clima e Segurança",
        "scan_bill" to "Escanear Fatura",
        "check_in" to "Registrar Entrada",
        "check_out" to "Registrar Saída",
        "create_project" to "Novo Projeto",
        "add_project" to "Adicionar Projeto",
        "create_task" to "Nova Tarefa",
        "add_task" to "Adicionar Tarefa",
        "add_expense" to "Registrar Despesa",
        "add_material" to "Adicionar Material",
        "add_staff" to "Adicionar Funcionário",
        "generate_report" to "Gerar Relatório",
        "voice_speak" to "Ditado por Voz",
        "role" to "Função",
        "language" to "Idioma",
        "budget" to "Orçamento",
        "spent" to "Gasto",
        "progress" to "Progresso",
        "search" to "Pesquisar...",
        "filter" to "Filtrar",
        "all" to "Todos",
        "active" to "Ativo",
        "planning" to "Planejamento",
        "completed" to "Concluído",
        "on_hold" to "Pausado",
        "save" to "Salvar",
        "cancel" to "Cancelar",
        "delete" to "Excluir",
        "edit" to "Editar",
        "status" to "Status",
        "priority" to "Prioridade",
        "present" to "Presente",
        "absent" to "Ausente",
        "half_day" to "Meio Período",
        "on_leave" to "De Licença",
        "overtime" to "Hora Extra",
        "late" to "Atrasado",
        "camera_scan" to "Escanear com Câmera",
        "ai_thinking" to "IA está pensando...",
        "ai_speaking" to "IA está falando...",
        "auto_speak" to "Voz Automática",
        "speak_again" to "Ouvir",
        "stop_speaking" to "Parar Áudio",
        "clear_history" to "Limpar Histórico",
        "voice_input" to "Fale em qualquer idioma",
        "quick_questions_title" to "Perguntas Rápidas IA",
        "dark_mode" to "Modo Escuro",
        "ai_suggestions" to "Sugestões IA",
        "voice_recognition" to "Reconhecimento de Voz",
        "reset_data" to "Restaurar Dados",
        "logout" to "Sair"
    )

    private val russianMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "Управление • Строительство • Успех",
        "dashboard" to "Панель",
        "projects" to "Проекты",
        "attendance" to "Посещаемость",
        "tasks" to "Задачи",
        "materials" to "Материалы",
        "expenses" to "Расходы",
        "staff" to "Персонал",
        "reports" to "Отчеты",
        "profile" to "Профиль",
        "settings" to "Настройки",
        "more" to "Еще",
        "ai_chat" to "ИИ-Помощник",
        "ai_fill" to "ИИ Автозаполнение",
        "ask_ai" to "Спросить ИИ",
        "today_attendance" to "Посещаемость сегодня",
        "ongoing_projects" to "Текущие проекты",
        "pending_tasks" to "Ожидающие задачи",
        "low_stock" to "Мало материалов",
        "project_health" to "Состояние проекта",
        "quick_actions" to "Быстрые действия",
        "ai_insights" to "ИИ Рекомендации",
        "weather_safety" to "Погода и безопасность",
        "scan_bill" to "Сканировать счет",
        "check_in" to "Отметить приход",
        "check_out" to "Отметить уход",
        "create_project" to "Новый проект",
        "add_project" to "Добавить проект",
        "create_task" to "Новая задача",
        "add_task" to "Добавить задачу",
        "add_expense" to "Добавить расход",
        "add_material" to "Добавить материал",
        "add_staff" to "Добавить сотрудника",
        "generate_report" to "Создать отчет",
        "voice_speak" to "Голосовой ввод",
        "role" to "Роль",
        "language" to "Язык",
        "budget" to "Бюджет",
        "spent" to "Потрачено",
        "progress" to "Прогресс",
        "search" to "Поиск...",
        "filter" to "Фильтр",
        "all" to "Все",
        "active" to "Активный",
        "planning" to "Планирование",
        "completed" to "Завершено",
        "on_hold" to "Приостановлен",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "delete" to "Удалить",
        "edit" to "Редактировать",
        "status" to "Статус",
        "priority" to "Приоритет",
        "present" to "Присутствует",
        "absent" to "Отсутствует",
        "half_day" to "Полдень",
        "on_leave" to "В отпуске",
        "overtime" to "Сверхурочные",
        "late" to "Опоздание",
        "camera_scan" to "Сканировать камерой",
        "ai_thinking" to "ИИ думает...",
        "ai_speaking" to "ИИ говорит...",
        "auto_speak" to "Автоозвучивание",
        "speak_again" to "Слушать",
        "stop_speaking" to "Остановить звук",
        "clear_history" to "Очистить историю",
        "voice_input" to "Говорите на любом языке",
        "quick_questions_title" to "Быстрые вопросы ИИ",
        "dark_mode" to "Темная тема",
        "ai_suggestions" to "ИИ-подсказки",
        "voice_recognition" to "Распознавание речи",
        "reset_data" to "Сброс данных",
        "logout" to "Выйти"
    )

    private val chineseMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "管理 • 建设 • 成功",
        "dashboard" to "仪表板",
        "projects" to "项目工程",
        "attendance" to "考勤打卡",
        "tasks" to "任务清单",
        "materials" to "材料库存",
        "expenses" to "财务支出",
        "staff" to "人员团队",
        "reports" to "报表分析",
        "profile" to "个人资料",
        "settings" to "系统设置",
        "more" to "更多",
        "ai_chat" to "AI 智能助手",
        "ai_fill" to "AI 自动填充",
        "ask_ai" to "咨询 SITE MAN AI",
        "today_attendance" to "今日考勤",
        "ongoing_projects" to "进行中项目",
        "pending_tasks" to "待办任务",
        "low_stock" to "库存预警",
        "project_health" to "工程健康指数",
        "quick_actions" to "快捷操作",
        "ai_insights" to "AI 智能洞察与建议",
        "weather_safety" to "工地天气与安全",
        "scan_bill" to "发票智能扫描",
        "check_in" to "上班打卡",
        "check_out" to "下班打卡",
        "create_project" to "新建项目",
        "add_project" to "添加项目",
        "create_task" to "新建任务",
        "add_task" to "添加任务",
        "add_expense" to "记录支出",
        "add_material" to "录入材料",
        "add_staff" to "录入人员",
        "generate_report" to "生成报表",
        "voice_speak" to "语音听写",
        "role" to "权限角色",
        "language" to "系统语言",
        "budget" to "预算资金",
        "spent" to "已用支出",
        "progress" to "工程进度",
        "search" to "搜索...",
        "filter" to "筛选",
        "all" to "全部",
        "active" to "进行中",
        "planning" to "规划中",
        "completed" to "已竣工",
        "on_hold" to "暂停",
        "save" to "保存",
        "cancel" to "取消",
        "delete" to "删除",
        "edit" to "编辑",
        "status" to "状态",
        "priority" to "优先级",
        "present" to "出勤",
        "absent" to "缺勤",
        "half_day" to "半天",
        "on_leave" to "请假",
        "overtime" to "加班",
        "late" to "迟到",
        "camera_scan" to "相机识别",
        "ai_thinking" to "AI 正在思考中...",
        "ai_speaking" to "AI 正在语音播报...",
        "auto_speak" to "自动语音朗读",
        "speak_again" to "朗读回答",
        "stop_speaking" to "停止播放",
        "clear_history" to "清空对话记录",
        "voice_input" to "支持任意语言语音输入",
        "quick_questions_title" to "AI 快捷提问",
        "dark_mode" to "深色模式",
        "ai_suggestions" to "AI 实时建议",
        "voice_recognition" to "语音识别",
        "reset_data" to "重置演示数据",
        "logout" to "退出登录"
    )

    private val japaneseMap = mapOf(
        "app_title" to "SITE MAN",
        "tagline" to "管理 • 施工 • 成功",
        "dashboard" to "ダッシュボード",
        "projects" to "プロジェクト",
        "attendance" to "出勤・勤怠",
        "tasks" to "タスク",
        "materials" to "資材管理",
        "expenses" to "経費・支出",
        "staff" to "作業員・スタッフ",
        "reports" to "レポート",
        "profile" to "プロフィール",
        "settings" to "設定",
        "more" to "その他",
        "ai_chat" to "AIアシスタント",
        "ai_fill" to "AI自動入力",
        "ask_ai" to "SITE MAN AIに質問",
        "today_attendance" to "本日の出勤状況",
        "ongoing_projects" to "進行中のプロジェクト",
        "pending_tasks" to "保留中のタスク",
        "low_stock" to "在庫不足アラート",
        "project_health" to "プロジェクト健全度",
        "quick_actions" to "クイック操作",
        "ai_insights" to "AI分析と提案",
        "weather_safety" to "現場の天気と安全",
        "scan_bill" to "請求書スキャン",
        "check_in" to "出勤打刻",
        "check_out" to "退勤打刻",
        "create_project" to "新規プロジェクト",
        "add_project" to "プロジェクト追加",
        "create_task" to "新規タスク",
        "add_task" to "タスク追加",
        "add_expense" to "経費追加",
        "add_material" to "資材追加",
        "add_staff" to "スタッフ追加",
        "generate_report" to "レポート生成",
        "voice_speak" to "音声入力",
        "role" to "権限ロール",
        "language" to "言語",
        "budget" to "予算",
        "spent" to "支出済",
        "progress" to "進捗率",
        "search" to "検索...",
        "filter" to "フィルター",
        "all" to "すべて",
        "active" to "進行中",
        "planning" to "計画中",
        "completed" to "完了",
        "on_hold" to "保留",
        "save" to "保存",
        "cancel" to "キャンセル",
        "delete" to "削除",
        "edit" to "編集",
        "status" to "ステータス",
        "priority" to "優先度",
        "present" to "出勤",
        "absent" to "欠勤",
        "half_day" to "半日",
        "on_leave" to "休暇",
        "overtime" to "残業",
        "late" to "遅刻",
        "camera_scan" to "カメラスキャン",
        "ai_thinking" to "AIが考えています...",
        "ai_speaking" to "AIが音声読み上げ中...",
        "auto_speak" to "自動音声読み上げ",
        "speak_again" to "読み上げる",
        "stop_speaking" to "音声を停止",
        "clear_history" to "履歴をクリア",
        "voice_input" to "どの言語でも音声入力可能",
        "quick_questions_title" to "クイックAI質問",
        "dark_mode" to "ダークモード",
        "ai_suggestions" to "AIサジェスト",
        "voice_recognition" to "音声認識",
        "reset_data" to "データリセット",
        "logout" to "ログアウト"
    )
}
